### ISSUE TITLE
Как установить на хостинг

### ISSUE THREAD

**Issue by Janikneo** [olton/Metro4-Sandbox#1]
Как установить на хостинг? там инструкции нету

**Comment by olton** [comment]
1) Скачать
2) Содержимое архива положить в соотвествующую папку на Вашем сервере (проконсультируйтесь с Вашим хостинг провайдером).
3) Из папки `Install` выполнить sql script на Вашем MySQL
4) В папке `Config` заполнить соотвествующие поля в маcсиве в файле database.php

**Comment by Janikneo** [comment]
Всё сделал так же, пустая страница выходит, не возможно отобразить страницу,

**Comment by Janikneo** [comment]
<?php

$db_config = array(
    'provider' => 'MySQL',
    'host' => 'localhost',
    'port' => '3306',
    'schema' => 'тут что писать?',
    'user' => 'пользователь',
    'password' => 'пароль'
);

return $db_config;

**Comment by olton** [comment]
В поле schema вписать название вашей базы данных

**Comment by Janikneo** [comment]
все так сделал

**Comment by olton** [comment]
Ну тут я Вам мало чем помогу, Вам нужно задать вопрос Вашему хостуре, что не так с настройками сервера, что скрипт песочницы не работает

**Comment by Janikneo** [comment]
что можно сделать

**Comment by Janikneo** [comment]
сделать

**Comment by olton** [comment]
Напрягайте саппорт хостинга

**Comment by olton** [comment]
дайте ссылку на Ваш сайт я посмотрю хотя бы лог браузера

**Comment by Janikneo** [comment]
шас минуту

**Comment by olton** [comment]
файл index.php из архива должен попасть в основную папку Вашего сайта, например у меня на хостинге это имя домена.

**Comment by Janikneo** [comment]
Я понимаю это

**Comment by olton** [comment]
Если Вы скачали с гитхаба, то внутри архива есть папка `Sandbox-master`. Содержимое этой папки должно попасть в основную папку Вашего сайта

**Comment by Janikneo** [comment]
Заливаю, я удалил, перезаливаю

**Comment by Janikneo** [comment]
dashboard.phtml это так и должно быть? или переименовать?

**Comment by olton** [comment]
ничего переименовывать не надо. я сейчас выложу версию с обновленной библиотекой Метро4

**Comment by Janikneo** [comment]
http://editor.icoder.uz/

**Comment by Janikneo** [comment]
Посмотрите вот там весь скрипт

**Comment by Janikneo** [comment]
о спасибо

**Comment by Janikneo** [comment]
Обновили?

**Comment by olton** [comment]
Я запушил апдейт, так что Вам нужно перекачать архив с гитхаба. Если хотите, давайте мне доступ к Вашему серверу я посмотрю. В браузере я вижу только, что сервер возвращает 500 ошибку. Это может значить все, что угодно.

**Comment by Janikneo** [comment]
Щас минуту

**Comment by olton** [comment]
Только пароли, если надумаете давать, давайте в личку sergey@pimenov.com.ua

**Comment by Janikneo** [comment]
ОК

**Comment by Janikneo** [comment]
Отправил

**Comment by Janikneo** [comment]
папка с таким же доменом

**Comment by Janikneo** [comment]
Перезалить файлы?

**Comment by olton** [comment]
Я сейчас сам перезалью

**Comment by Janikneo** [comment]
А системные требования какие должны быть?

**Comment by olton** [comment]
Перезаливаю. PHP не ниже 5-й версии, лучше 7-я

**Comment by olton** [comment]
Странно то, что я даже не могу запустить простой скрипт с одно функцией phpinfo http://editor.icoder.uz/info.php, выдает 500 ошибку.

**Comment by olton** [comment]
Я сейчас на час уйду, у меня запись к зубному, вернусь, продолжим....

**Comment by Janikneo** [comment]
Завтра во сколько вы будете около компа?

**Comment by Janikneo** [comment]
Просто я не дома

**Comment by olton** [comment]
с 10 часов GMT+2

**Comment by Janikneo** [comment]
Я на этот домен настраивал ruby приложение, но потом удалил, может изза этого?

**Comment by Janikneo** [comment]
Хотя домен пересоздал

**Comment by Janikneo** [comment]
Parse error: syntax error, unexpected 'List' (T_LIST), expecting identifier (T_STRING) in /home/icoderuz/editor.icoder.uz/Models/CodeModel.php on line 156 вот эта ошибка это что

**Comment by olton** [comment]
Для начала нужно запустить  скрипт info.php . Напишите в саппорт хостинга, пусть объяснят почему не запускается. Потом будем дальше копать. Проблема точно в настройках хостинга.

**Comment by Janikneo** [comment]
Заработал, теперь одна ошибка Веб-страница по адресу https://editor.icoder.uz/Sandbox/temp/Admin-metro4-5c5b04646b140.html, возможно, временно недоступна или постоянно перемещена по новому адресу.

**Comment by Janikneo** [comment]
http://editor.icoder.uz/

**Comment by olton** [comment]
Ну все работает. Для авторизации через гитлаб и гитхаб нужно получить соотвествующие ключи и вписать их в фалы `GithubOAuthConfig.php` и `GitlabOAuthConfig.php` в папке `Controllers`

**Comment by Janikneo** [comment]
Адресная строка красная, Не защищено написано это от чего?

**Comment by olton** [comment]
Это нужно включить https

**Comment by Janikneo** [comment]
.htaccess?

**Comment by olton** [comment]
1) получить сертификат SSL
2) загрузить ега на сервыер хотинга (как, спросить у саппорта)
3) включить поддержку https протокола (как, спросить у саппорта)
4) в файле .htaccess раскоментировать строки про https, подставив данные своего домена

**Comment by olton** [comment]
убрать #

**Comment by Janikneo** [comment]
У меня есть сертификат, бесплатно выдали когда приобрёл хостинг

**Comment by Janikneo** [comment]
Не меняется

**Comment by olton** [comment]
Ну тут я Вам точно не помогу, пишите в саппорт хостинга

**Comment by Janikneo** [comment]
Ок спасибо огромное

**Comment by Janikneo** [comment]
Вы ещё создали базу данных? у меня 4 есть а показывает что 5 использовано

**Comment by olton** [comment]
Да я создал БД _sandbox и привязал ее к скриптам песочницы

**Comment by olton** [comment]
Так же я изменил права на папку Sandbox на 777

**Comment by Janikneo** [comment]
Она видна,

**Comment by Janikneo** [comment]
Спасибо за отзывчивость и за помощь, редко встречаются такие авторы

**Comment by Janikneo** [comment]
Всё что лишнее можете удалить

**Comment by Janikneo** [comment]
А можно вопрос, коды других пользователей не видно, это так задумано? То есть я вижу только свои коды, коды других мне не видно

**Comment by olton** [comment]
Пока только свои
