### ISSUE TITLE
Коды других пользователей не видно

### ISSUE THREAD

**Issue by Janikneo** [olton/Metro4-Sandbox#2]
А можно вопрос, коды других пользователей не видно, это так задумано? То есть я вижу только свои коды, коды других мне не видно

**Comment by olton** [comment]
Пока видимости прямой чужих кодов нет. К чужим можно достучаться по ссылке, человек копирует ссылку из браузера н асвой код и дает вам, вы мо ней переходите, можете играться, можете сделать форк.

**Comment by Janikneo** [comment]
А форк как переводится?

**Comment by olton** [comment]
Копия

**Comment by Janikneo** [comment]
Понял, планируете на главную показ коды всех пользователей?

**Comment by olton** [comment]
Да, будет по типу как на codepen.io

**Comment by Janikneo** [comment]
ООО классно, ждёмс тогда, я тоже попробую

**Comment by Janikneo** [comment]
Как можно будет узнать о том что сделано? тут я новичок

**Comment by olton** [comment]
следите за обновлениями на гитхабе

**Comment by Janikneo** [comment]
Не терпится, а это скоро? Извините

**Comment by olton** [comment]
Не знаю, у меня 5 проектов одновремеено в работе

**Comment by Janikneo** [comment]
Надо хотя бы админку сделать, там и всё собрать, чтоб каждый раз не лезть в базу данных посмотреть не нагадил ли кто

**Comment by Janikneo** [comment]
Ещё какие есть, можно посмотреть?

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS
https://github.com/olton/Metro4-M4Q
https://github.com/olton/m4q
https://github.com/olton/Metro4-Builder
https://github.com/olton/FireKit
https://github.com/olton/Sandbox

**Comment by Janikneo** [comment]
Здравствуйте, а с вами как напрямую связаться, телеграм или похожее есть?

**Comment by Janikneo** [comment]
есть пару вопросов не касающиеся этой темы

**Comment by olton** [comment]
Здравствуйте. У меня очень много работы, поэтому я никому не даю свои прямые контакты.
