### ISSUE TITLE
Изменения

### ISSUE THREAD

**Issue by Janikneo** [olton/Metro4-Sandbox#4]
Здравствуйте, изменений нет пока?

**Comment by Janikneo** [comment]
Есть ли обновления?

**Comment by olton** [comment]
В песочнице изменений нет, занят фиксами в основной библиотеке

**Comment by Janikneo** [comment]
Здравствуйте, изменений нет? Столько месяцев прошло, может, есть новости

**Comment by olton** [comment]
Здравствуйте! К сожалению у меня нет времени на песочницу. Все время уходит на Metro4: на фиксы 4.2.х версии и разработку 4.3.х. Теперь еще и версию под React начал. Так что пока песочница и билдер отложены до непонятно какого времени.
